import time
def levenshteinovaRazdalja_DP(beseda1, beseda2):
    """
    Izracuna levensteinovo razdaljo za dve besedi oziroma stevilo operacij (dodaj, odstrani, zamenjaj),
    da iz prve naredimo drugo. To naredimo z pomocjo DP oziroma matrike.
    """
    razdalje = [[0 for i in range(len(beseda2) + 1)] for j in range(len(beseda1) + 1)]

    #cena sestavljanja iz praznega niza besede1
    for i in range(len(beseda1) + 1):
        razdalje[i][0] = i

    #cena sestavljanja iz praznega niza besede2
    for j in range(len(beseda2) + 1):
        razdalje[0][j] = j
    
    #primerjamo prejsnjega sestavljanja in vzamemo najmanjso stevilo operacij
    #v primeru, da se znaka razlikujeta pristejemo se 1 ker naredimo novo operacijo   
    for i in range(1, len(beseda1) + 1):
        for j in range(1, len(beseda2) + 1):
            if (beseda1[i-1] == beseda2[j - 1]):

                #v primeru da sta enaki potem imamo na diagonali bo vedno najmanjsa iz prejsnje iteracije
                razdalje[i][j] = razdalje[i - 1][j - 1]
            else:
                levo = razdalje[i][j - 1]
                gor = razdalje[i - 1][j]
                diagonala = razdalje[i - 1][j - 1]
                
                razdalje[i][j] = min(levo, gor, diagonala) + 1

    return razdalje[len(beseda1)][len(beseda2)]

#print(levenshteinovaRazdalja_DP("borba", "torba"))


zac = time.time()
for _ in range(100):
    levenshteinovaRazdalja_DP("ab" * 100, "cd" * 100)


konc = time.time() - zac
print(konc / 100)


"""
print(levenshteinovaRazdalja_DP("ab" * 500, "cd" * 100))
print(levenshteinovaRazdalja_DP("ab" * 500, "cd" * 1000))
print(levenshteinovaRazdalja_DP("ornitologija" * 420, "otorinolaringolog" * 60))
print(levenshteinovaRazdalja_DP("DonaudampfasrinolarindsDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftDonaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaftchiffarinolarinhrtselektrizitätrinolarinenhauptbetriebswerkbauunterbeamtengesellschaft", "Donaausddarinolarinsdamaspdfasgcrinolarinasghawiefffahrtsgesellschaftskapitän"))
"""